Fixed a fatal bug in spider.py when name resolution fails again and again. Here is a traceback I caught for which Persepolis would crash.
~ $ persepolis  # After a while trying to fetch file-name & size the error was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 787, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f59da1f2710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='r4---sn-npoe7n7z.googlevideo.com', port=443): Max retries exceeded with url: /videoplayback?signature=53250B11B8FC0DC28134F46B90805B6F03C60233.5B67B035B0D55D3E2F04EF8CF5C8F6C21E8A082E&ipbits=0&initcwndbps=67500&pl=24&key=yt6&ip=103.94.130.2&ei=r0NCWt4iwqyiA_fHmsAB&requiressl=yes&itag=43&source=youtube&clen=389565127&ms=au&mt=1514292048&mv=m&id=o-ABeg11yteOZHlAQFBBQOgmQl9GBneByW-tnqcfCdRAZe&dur=0.000&gir=yes&mime=video%2Fwebm&mn=sn-npoe7n7z&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&lmt=1514268303574223&expire=1514313743&ratebypass=yes&mm=31 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f59da1f2710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/persepolis-3.0.1-py3.5.egg/persepolis/scripts/youtube_addlink.py", line 347, in run
  File "/usr/local/lib/python3.5/dist-packages/persepolis-3.0.1-py3.5.egg/persepolis/scripts/spider.py", line 72, in spider
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 500, in head
    return self.request('HEAD', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='r4---sn-npoe7n7z.googlevideo.com', port=443): Max retries exceeded with url: /videoplayback?signature=53250B11B8FC0DC28134F46B90805B6F03C60233.5B67B035B0D55D3E2F04EF8CF5C8F6C21E8A082E&ipbits=0&initcwndbps=67500&pl=24&key=yt6&ip=103.94.130.2&ei=r0NCWt4iwqyiA_fHmsAB&requiressl=yes&itag=43&source=youtube&clen=389565127&ms=au&mt=1514292048&mv=m&id=o-ABeg11yteOZHlAQFBBQOgmQl9GBneByW-tnqcfCdRAZe&dur=0.000&gir=yes&mime=video%2Fwebm&mn=sn-npoe7n7z&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&lmt=1514268303574223&expire=1514313743&ratebypass=yes&mm=31 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f59da1f2710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Aborted

Signed-off-by: chitholian <chitholian@gmail.com>